GET http://localhost:3000/api/employees

GET http://localhost:3000/api/employees/684c8bd02ae4e5f0333939af

POST http://localhost:3000/api/employees
Content-Type: application/json

{
  "fullName": "Juan Perez",           
  "role": "Supervisor de obra",                 
  "seniority": 5,            
  "availableHours": 40,
  "salary": 50000,
  "overtimeHours": 5,        
  "performanceScore": 90,     
  "assignedTasks": ["planting"],
}

PUT http://localhost:3000/api/employees/684b9907d79c41bdd6f62e03
Content-Type: application/json

{
 "fullName": "Juan Perez",           
 "role": "Supervisor de obra",                 
 "seniority": 5,            
 "availableHours": 40,       
 "salary": 50000,
 "overtimeHours": 5,        
 "performanceScore": 90,     
 "assignedTasks": ["planting"],
}

PATCH http://localhost:3000/api/employees/684b9907d79c41bdd6f62e03
Content-Type: application/json

{
  "role": "Encargado de mantenimiento",
  "overtimeHours": 10
}

DELETE http://localhost:3000/api/employees/684b9907d79c41bdd6f62e03
